; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[project]
version = 1.0.1

[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
; Arduino-ESP32 3.2.0 / ESP-IDF 5.4.x
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.312/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino

monitor_speed = 115200
upload_protocol = esptool

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; Quad flash + Octal PSRAM
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -D CURRENT_VERSION=\"${project.version}\"
    -D OTA_URL=\"https://kubis15.github.io/ArdEspIDF_OTA/\"

lib_ignore =
    ESPAsyncTCP
    RPAsyncTCP
    
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.15.5
    bblanchon/ArduinoJson @ 7.4.3
    ESP32Async/AsyncTCP @ ^3.5.0
    ESP32Async/ESPAsyncWebServer @ ^3.12.0
   

upload_port = COM7
upload_speed = 921600
