; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[project]
version = 1.0.3

[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32 @ ^6.13.0  ; Version 6.x+ uses ESP-IDF v5.x
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_protocol = esptool

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; Quad flash + Octal PSRAM
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -D CURRENT_VERSION=\"${project.version}\"
    -D OTA_URL=\"https://kubis15.github.io/ArdEspIDF_OTA/\"


lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.15.5
    bblanchon/ArduinoJson @ 7.4.3

upload_port = COM7
upload_speed = 921600
